name: chat_it
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  dio: ^4.0.6
  flutter_signin_button: ^2.0.0
  dropdown_button2: ^1.7.2
  flutter_chat_ui: ^1.6.4
  file_picker: ^5.0.1
  image_picker: ^0.8.5+3
  mime: ^1.0.2
  uuid: ^3.0.6
  better_open_file: ^3.6.3
  bubble: ^1.2.1
  google_sign_in: ^5.4.1
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  flutter_firebase_chat_core: ^1.6.3
  firebase_storage: ^10.3.6
  lottie: ^1.4.1
  scroll_page_view: ^1.0.2
  flutter_launcher_icons: ^0.10.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



  # To add assets to your application, add an assets section, like this:
 

flutter: 
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
  

  assets:
   - assets/icons/
   - assets/lottie/

