name: chat_it
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.3
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  dio: ^4.0.6
  flutter_signin_button: ^2.0.0
  dropdown_button2: ^1.7.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

